name: Share data between jobs

on: [push]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > addition.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          path: addition.txt

  job_2:
    name: Multiply by 9
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "I'm lazy, just send you the factor ..."
          echo "9" > factor.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v3
        with:
          path: factor.txt

  job_3:
    name: Display results
    needs: [ job_1, job_2 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - name: Print the final result
        shell: bash
        run: |
          ls
          value=`cat addition.txt`
          factor=`cat factor.txt`
          total=$(expr $value \* $factor)
          echo "The result is $total"

